language: node_js
node_js:
  - "node"

script:
  - yarn lint
  - yarn flow

deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script:
    - yarn build
    - now build --public --name pakutin-yard-frontend --token $NOW_TOKEN
    - now alias --token $NOW_TOKEN