// flow-typed signature: 9e6056dee394d35e1f6702ba5407856d
// flow-typed version: <<STUB>>/react-flexboxgrid_v^1.0.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-flexboxgrid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-flexboxgrid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-flexboxgrid/dist/react-flexboxgrid' {
  declare module.exports: any;
}

declare module 'react-flexboxgrid/dist/react-flexboxgrid.min' {
  declare module.exports: any;
}

declare module 'react-flexboxgrid/karma.conf' {
  declare module.exports: any;
}

declare module 'react-flexboxgrid/lib/Col' {
  declare module.exports: any;
}

declare module 'react-flexboxgrid/lib/Grid' {
  declare module.exports: any;
}

declare module 'react-flexboxgrid/lib/index' {
  declare module.exports: any;
}

declare module 'react-flexboxgrid/lib/Row' {
  declare module.exports: any;
}

declare module 'react-flexboxgrid/postcss.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-flexboxgrid/dist/react-flexboxgrid.js' {
  declare module.exports: $Exports<'react-flexboxgrid/dist/react-flexboxgrid'>;
}
declare module 'react-flexboxgrid/dist/react-flexboxgrid.min.js' {
  declare module.exports: $Exports<'react-flexboxgrid/dist/react-flexboxgrid.min'>;
}
declare module 'react-flexboxgrid/karma.conf.js' {
  declare module.exports: $Exports<'react-flexboxgrid/karma.conf'>;
}
declare module 'react-flexboxgrid/lib/Col.js' {
  declare module.exports: $Exports<'react-flexboxgrid/lib/Col'>;
}
declare module 'react-flexboxgrid/lib/Grid.js' {
  declare module.exports: $Exports<'react-flexboxgrid/lib/Grid'>;
}
declare module 'react-flexboxgrid/lib/index.js' {
  declare module.exports: $Exports<'react-flexboxgrid/lib/index'>;
}
declare module 'react-flexboxgrid/lib/Row.js' {
  declare module.exports: $Exports<'react-flexboxgrid/lib/Row'>;
}
declare module 'react-flexboxgrid/postcss.config.js' {
  declare module.exports: $Exports<'react-flexboxgrid/postcss.config'>;
}
