// flow-typed signature: 5a9f83b5a8ffcfbe7e4ad809cbec139b
// flow-typed version: <<STUB>>/ruplu_v^2.0.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ruplu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ruplu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ruplu/src/modules/handler' {
  declare module.exports: any;
}

declare module 'ruplu/src/ruplu' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ruplu/index' {
  declare module.exports: $Exports<'ruplu'>;
}
declare module 'ruplu/index.js' {
  declare module.exports: $Exports<'ruplu'>;
}
declare module 'ruplu/src/modules/handler.js' {
  declare module.exports: $Exports<'ruplu/src/modules/handler'>;
}
declare module 'ruplu/src/ruplu.js' {
  declare module.exports: $Exports<'ruplu/src/ruplu'>;
}
